apiVersion: v1
entries:
  dps:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-09T08:05:44.564658502Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: d436051b6db233d8c1f94cc124a35824e14fc34a53c94dab5fa40ba76de5f905
    home: dps.zaakonline.nl
    icon: dps.zaakonline.nl
    name: dps
    urls:
    - dps-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-09T08:05:44.561058502Z"
